### ISSUE TITLE
🧠 Logic: Lack of information when `ErrorOutOfGas` in interpreter

### ISSUE THREAD

**Issue by bdeneux** [axone-protocol/axoned#692]
### 📝 Description

When executing a predicate that results in an `ErrorOutOfGas`, the error message provided is misleading and lacks clarity. Specifically, the error message returned is a generic panic message (`panic: {ValuePerByte}`) that does not accurately reflect the underlying issue of running out of gas during the predicate's execution. 

### 🔎 Example to Illustrate the Issue

Executing the following query results in an error message that does not clearly indicate the `ErrorOutOfGas` condition:

```bash
axoned query logic ask "findall(Pred, bank_balances(T, U), Pred)."
```

The response includes a vague error message:

```yaml
answer:
  has_more: false
  results:
  - error: 'panic: {ValuePerByte}'
    substitutions: []
  variables:
  - Pred
  - T
  - U
gas_used: "100038"
height: "10194"
user_output: ""
```

The error message `- error: 'panic: {ValuePerByte}'` is not informative regarding the actual issue, which is an `ErrorOutOfGas` encountered during the retrieval of all balances within the interpreter.

### ⚙️ Technical Explanation and Current Handling

The mechanism for catching an `ErrorOutOfGas` is implemented but only triggers if the gas consumption limit is reached based on the predicate cost prior to the execution of the requested predicate. 

https://github.com/axone-protocol/axoned/blob/279b2ee73f89bd648e3489821b8dcce209665d35/x/logic/keeper/interpreter.go#L108-L117

However, this handling does not account for gas exhaustion that occurs during the execution of a predicate. As a result, when the gas limit is exceeded within the predicate execution, the error reported is the panic description catch by prolog interpreter.

FYI @ccamel @amimart
